In [3]:
import pandas as pd
import numpy as np



In [4]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [11]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1:3, 2]

array([12, 47])

In [79]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
sum(big_secret[:, -1])

3154.332495807108

In [19]:
sum(np.diagonal(big_secret[:5]))


121.37188663699624

In [32]:
np.prod(np.diagonal(big_secret[:, -5:]))


341505315559.2347

In [41]:
my_array = np.random.randint(1, 100, (4, 6))
print(my_array)
my_slice = my_array[1:3, 2:4]
print(my_slice)
my_slice[:] = 0

[[88 59  4 24 92 79]
 [22 69 39 62  6 55]
 [10  8 74 27 72 10]
 [25  1 91 70 93 14]]
[[39 62]
 [74 27]]


In [83]:
print(big_secret)

even = big_secret[::2,::2]
even[:] = -1
uneven = big_secret[1::2,1::2]
uneven[:] = 1

[[1.40000000e+01 1.00000000e+01 6.00000000e+00 5.60000000e+01
  4.00000000e+01 2.40000000e+01 9.80000000e+01 7.00000000e+01
  4.20000000e+01 1.40000000e+02 1.00000000e+02 6.00000000e+01
  1.82000000e+02 1.30000000e+02 7.80000000e+01 2.24000000e+02
  1.60000000e+02 9.60000000e+01 2.66000000e+02 1.90000000e+02
  1.14000000e+02 3.08000000e+02 2.20000000e+02 1.32000000e+02
  3.50000000e+02 2.50000000e+02 1.50000000e+02 3.92000000e+02
  2.80000000e+02 1.68000000e+02 4.34000000e+02 3.10000000e+02
  1.86000000e+02 4.76000000e+02 3.40000000e+02 2.04000000e+02
  5.18000000e+02 3.70000000e+02 2.22000000e+02 5.60000000e+02
  4.00000000e+02 2.40000000e+02 6.02000000e+02 4.30000000e+02
  2.58000000e+02 6.44000000e+02 4.60000000e+02 2.76000000e+02
  6.86000000e+02 4.90000000e+02 2.94000000e+02]
 [3.16227766e+01 3.16543836e+01 3.16859590e+01 3.17175031e+01
  3.17490157e+01 3.17804972e+01 3.18119474e+01 3.18433667e+01
  3.18747549e+01 3.19061123e+01 3.19374388e+01 3.19687347e+01
  3.20000000e+01 3.203

In [86]:
sum(np.diagonal(big_secret[:,:5]))
np.prod(np.diagonal(big_secret[:, -5:]))


-1.0

In [87]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+bmy_array = np.random.randint(0, 10, (3,4))result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [91]:
my_array = np.random.randint(0, 10, (3,4))
print(my_array)
print(my_array<5)
print(my_array[my_array<5])

[[6 6 6 7]
 [0 6 9 7]
 [5 3 8 5]]
[[False False False False]
 [ True False False False]
 [False  True False False]]
[0 3]


In [93]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

great_secret.shape


(100, 3)

In [95]:
sum(np.cos(great_secret[0]))

0.16006721889793019

In [96]:
sum(great_secret[great_secret>50])

5470.0

In [103]:
great_secret.flatten()[150]



7.0710678118654755

In [108]:
sum(np.sort(great_secret, axis=0)[-1])



115.12148016521353

In [117]:
students = np.array([
    [1, 135, 34, 4],
    [2,	160, 43, 5],
    [3,	163, 40, 4.3],
    [4,	147, 44, 5],
    [5,	138, 41, 4.7],
    [6,	149, 54, 3.9],
    [7,	136, 39, 4.2],
    [8,	154, 48, 4.9],
    [9,	137, 35, 3.7],
    [10, 165, 60, 4.6]])

students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [118]:
mean = np.mean(students[:,-1])
mean



4.430000000000001

In [121]:
np.mean(students[:,-2]) - np.median(students[:,-2])

1.7999999999999972

In [125]:
corr_height_mass = np.corrcoef(students[:,1], students[:,2])
print(corr_height_mass)

corr_height_grades = np.corrcoef(students[:,1], students[:,3])
print(corr_height_grades)

corr_mass_grades = np.corrcoef(students[:,2], students[:,3])
print(corr_mass_grades)

[[1.         0.64314431]
 [0.64314431 1.        ]]
[[1.         0.46293714]
 [0.46293714 1.        ]]
[[1.         0.29801325]
 [0.29801325 1.        ]]


In [127]:
std = np.std(students[:,3])
std


0.4517742799230607

In [138]:
print(np.std(students[:,2])**2)




60.36


In [145]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_array[1:-1,1:-1]

my_sin = np.sin(my_array)
center = my_sin[1:-1,1:-1]
center[:] = 1
sum(my_sin.flatten())

7.5717184212691455

In [152]:
sum(np.reshape(my_sin[:,:4], (10, 2))[:,0])



2.4057172058139544

In [168]:
bigdata = np.array([x**2 for x in range(101, 1001, 2)])
np.median(bigdata)
np.std(bigdata)

np.corrcoef(bigdata[::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])