In [87]:
import pandas as pd
import numpy as np

def echo(data, comment=''):
    print(comment, ','.join([str(int(x)) for x in list(data)]))

apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

share_living_space = apartment[1]/apartment[0]

share_living_space

0.5277310924369748

In [88]:
df = pd.DataFrame({'rent': [65, 70, 120, 35, 40, 50, 100, 90, 85],
                                'area': [50, 52, 80, 33, 33, 44, 80, 65, 65],
                                'rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                'floor':[5, 12, 10, 3, 6, 13, 8, 21, 5],
                                'demos':[8, 4, 5, 10, 20, 12, 5, 1, 10],
                                'living_area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [89]:
df.iloc[4].values

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [90]:
df['floor'].values

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [91]:
df

rent  area  rooms  floor  demos  living_area
0    65    50      3      5      8           37
1    70    52      2     12      4           40
2   120    80      1     10      5           65
3    35    33      1      3     10           20
4    40    33      1      6     20           16
5    50    44      2     13     12           35
6   100    80      4      8      5           60
7    90    65      3     21      1           50
8    85    65      2      5     10           40

In [92]:
df['area'].values - df['living_area'].values

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [93]:
df['rent'].values/10*4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [94]:
df['demo_lengh_min'] = [10,20,30,15,5,40,20,8,20]
(df['demos'] * df['demo_lengh_min']).sum()

1348

In [95]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

print('u@v', u@v)
print('u@w', u@w)
print('v@w', v@w)

echo(v*2 + w*-3)

(v*2 + w*-3)@u

print('u', u / ((u@u) ** (1/2)))
print('v', v / ((v@v) ** (1/2)))
print('w', w / ((w@w) ** (1/2)))

u@v 0
u@w 0
v@w 0
 -3,14,3,4,2
u [0.8660254  0.         0.28867513 0.28867513 0.28867513]
v [ 0.          0.33333333  0.          0.66666667 -0.66666667]
w [ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]


In [96]:
u_norm=u/np.linalg.norm(u)

v_norm=v/np.linalg.norm(v)

w_norm=w/np.linalg.norm(w)

print(u_norm[2])

print(v_norm[3])

print(w_norm[0])

0.2886751345948129
0.6666666666666666
0.21320071635561041


In [97]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).T

Tax = Inc * 0.13

Rev = Inc - Tax

In [98]:
P = Rev - Cons

P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [99]:
a = np.array([[1,-1,2,4,0], [8,2,0,5,3], [0,1,2,1,2]])

b = np.array([[1,0,1,0], [0,0,2,-1], [1,0,1,1], [0,1,1,1], [1,1,0,-1]])

a@b

a = np.array([1,3], ndmin=2)
b = np.array([-3,1], ndmin=2)

a.T@b

array([[-3,  1],
       [-9,  3]])

In [100]:
a = np.array([1,1])
b = np.array([2,-1])
c = np.array([1,2])

np.array([[a@a, a@b, a@c], [b@a, b@b, b@c], [c@a, c@b, c@c]])

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

In [101]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x0 = np.array([1,2,3,4,5])
x1 = np.array([1,2,3,4,5], ndmin=2).T

print(A@x0)
print(A@x1)

[26 30]
[[26]
 [30]]


In [102]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )

A.shape
B.shape

B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [103]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A = np.array([x,y,z]).T

print(A)

A.T@A

[[ 1  2 -1]
 [ 2  1  1]
 [ 1 -1 -1]
 [ 0  1  0]
 [ 4  0  0]]


array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [104]:
x_norm = x/np.linalg.norm(x)
y_norm = x/np.linalg.norm(y)
z_norm = x/np.linalg.norm(z)

print(x / (x@x) ** (1/2))
print(x_norm)

A_norm = np.array([x_norm,y_norm,z_norm]).T

A_norm.T@A_norm

[0.21320072 0.42640143 0.21320072 0.         0.85280287]
[0.21320072 0.42640143 0.21320072 0.         0.85280287]


array([[1.        , 1.77281052, 2.7080128 ],
       [1.77281052, 3.14285714, 4.80079359],
       [2.7080128 , 4.80079359, 7.33333333]])

In [105]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7],
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0],
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                },
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5],
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4],
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2]
                                },
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

print(Count_DF.loc['Борис'].values)
print(Price_DF.loc['Борис'].values)

print(Count_DF.loc['Борис'].values * Price_DF.loc['Борис'].values)



[ 2 21  3 25  6]
[1.8 2.5 1.  1.  1. ]
[ 3.6 52.5  3.  25.   6. ]


In [113]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])


print(Count_DF.values)

print(Price_DF.values)

(Count_DF.values * Price_DF.values)@(np.ones(5)-com)

[[10  5 12 15 10]
 [ 2 21  3 25  6]
 [12 12  0 30  4]
 [ 4  8 18 14  5]
 [ 6 25 27 25 18]
 [10  3  2 17 12]
 [22  1  4 25 20]
 [ 7  0 31 31 28]]
[[2.  1.5 1.  0.8 1. ]
 [1.8 2.5 1.  1.  1. ]
 [2.  2.  0.  0.5 2. ]
 [1.8 1.2 2.8 0.8 2. ]
 [2.5 3.5 2.  1.  1.5]
 [5.  5.  3.  2.  2.5]
 [1.1 1.  1.5 0.5 1.7]
 [4.5 4.  2.5 1.  2. ]]


array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [118]:
A = np.array([A,[2,5]])

np.linalg.inv(A)

array([[ 5., -2.],
       [-2.,  1.]])

In [120]:
A = np.array([[2,0,0],[0,1,0],[0,0,4]])
Ai = np.linalg.inv(A)

print(np.linalg.det(A))
print(np.linalg.det(Ai))

7.999999999999998
0.12500000000000003


In [144]:
A = np.array([[4,1,3],[1,5,0],[0,0,1]])
v = np.array([0,0,0])

print(np.linalg.inv(A))
#print(np.linalg.solve(A,v))



[[ 0.55555556 -0.11111111 -1.66666667]
 [-0.11111111  0.22222222  0.33333333]
 [ 0.          0.          1.        ]]


In [128]:
A = np.array([[3,-2,4],[3,4,-2],[2,-1,-1]])
v = np.array([21,9,10])

print(np.linalg.solve(A,v))

[ 5. -1.  1.]


In [141]:
A = np.array([[1,4,7,0],[2,5,8,0],[3,6,9,0],[1,1,1,0]])
v = np.array([0,0,0,0])

print(np.linalg.det(A).round())
#print(np.linalg.solve(A,v))

0.0


In [147]:
A=np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])

print(np.linalg.inv(A).round(3))

[[-1.875  2.312 -0.031]
 [ 0.375 -0.562  0.156]
 [ 1.25  -1.375 -0.062]]


In [157]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

A = np.array([v1,v2,v3,v4]).T

np.linalg.matrix_rank(A)

A_gr = A.T@A
np.linalg.det(A_gr).round()

np.linalg.inv(A_gr).round(3)


array([[ 0.017, -0.028, -0.026,  0.016],
       [-0.028,  0.072,  0.03 , -0.027],
       [-0.026,  0.03 ,  0.077, -0.026],
       [ 0.016, -0.027, -0.026,  0.035]])